### ISSUE TITLE
Should use pagination to find more than (default) 30 files on a PR

### ISSUE THREAD

**Issue by ruudk** [gkampitakis/github-action-todo-commenter#19]
I noticed that the action doesn't work on a PR with 1100 files. 

I saw the following on the documentation:
> List pull requests files
> Note: Responses include a maximum of 3000 files. The paginated response returns 30 files per page by default.
[source](https://octokit.github.io/rest.js/v20#pulls-list-files)

I believe the action should use pagination as described here:
https://octokit.github.io/rest.js/v20#pagination

https://github.com/gkampitakis/github-action-todo-commenter/blob/16afed710f55326de142a4bc6b4fa97e16359db4/src/pr-files.ts#L17-L24

**Comment by gkampitakis** [comment]
🤔  if it returns 3000 files then why it didn't work with 1100 files? Was there maybe another issue?

**Comment by ruudk** [comment]
It did not work on my PR, because the action only saw 30 files. As this is the default page size, and no pagination was used.

It has nothing to do with my PR having 1100 files and the upper limit of 3000 (paginatable) files.

**Comment by gkampitakis** [comment]
Sorry misread your description. Thanks for the pr. I have commented there with the updated test and one comment.
