### ISSUE TITLE
Only report new todo's, not existing todo's in files that changed

### ISSUE THREAD

**Issue by ruudk** [gkampitakis/github-action-todo-commenter#21]
Let's say you have a todo in a file that is in the `main` branch.

You now create a new branch, and modify that file, and make some changes without touching the todo.

On the PR, it will now comment that you have a todo in that file.

Is that expected? I think not.

In my opinion it should ignore existing todo's that are in the base branch.

**Comment by gkampitakis** [comment]
Hey 👋  thanks for opening this issue and all the prs and discussions. I would swear this is already how this works https://github.com/gkampitakis/github-action-todo-commenter/pull/9. Maybe there is a weird edge case?
