### ISSUE TITLE
Make action only run on `git diff`

### ISSUE THREAD

**Issue by kutyel** [gkampitakis/github-action-todo-commenter#8]
Hi! We wanted to use this GH action but we noticed it runs on all the modified files and that is a bit inconvenient for us since many things appear that are not related to the current PR. 🙏🏻

**Comment by gkampitakis** [comment]
Hey 👋 , thanks for opening this issue. 

I am not sure I am following up with what exactly is the problem, if you can give me more information I am happy to help.

The way it currently works is 
https://github.com/gkampitakis/github-action-todo-commenter/blob/43ec5c2a7f26dca729c86e1cc9caef41d0f213f4/src/pr-files.ts#L10-L15

getting all the diffs for the pull request and ignoring `removed` and `unchanged` files. What would be the difference with the `git diff`?

**Comment by kutyel** [comment]
I think the current behaviour gives you ALL the files (and lines) that have been modified for that PR, but the file could have already TODO's that are not part of your current `git diff`. So you did not change that part of the code but this extension warns you that previous code from that FILE has TODOs. Ideally you just want to know about the TODO's that were introduced with your changes so that they are fixed (or created JIRA/Github tickets for) as part of your code changes, right?

**Comment by gkampitakis** [comment]
Ohh I see your point. You are right this is the current behavior. Didn't think about that case going to have a look at it.
